# Generated by Django 5.0.4 on 2024-05-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friender', '0003_hotels_persons_book_order_info_hotel_owner_hobbies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel_owner',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='hotel_owner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hotel_owner',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='persons',
        ),
        migrations.AddField(
            model_name='hotelscomment',
            name='hotel_rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelscomment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelscomment',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='friender.hotels'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='serial',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='BookOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200, null=True)),
                ('time_order', models.DateTimeField(auto_now_add=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='friender.hotels')),
            ],
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='friender.user')),
                ('owner_exp_status', models.IntegerField(null=True)),
            ],
            bases=('friender.user',),
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='friender.user')),
                ('guest_rating', models.IntegerField(null=True)),
            ],
            bases=('friender.user',),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='owners',
            field=models.ManyToManyField(related_name='hobbies', to='friender.user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='persons',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='friender.user'),
        ),
        migrations.CreateModel(
            name='PersonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('person_rating', models.PositiveIntegerField(null=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_comments', to='friender.hotels')),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_comments', to='friender.persons')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Book_order_info',
        ),
        migrations.DeleteModel(
            name='Hotel_owner',
        ),
        migrations.AddField(
            model_name='hotels',
            name='owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='friender.hotelowner'),
        ),
        migrations.AddField(
            model_name='bookorderinfo',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='friender.persons'),
        ),
        migrations.AlterField(
            model_name='hotelscomment',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='friender.persons'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
