# Generated by Django 5.0.6 on 2024-05-28 07:59

import friender.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friender', '0006_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[friender.validators.users_age_validator]),
        ),
    ]
