# Generated by Django 5.0.6 on 2024-06-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friender', '0010_queue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
